version: '1.0.1'
services:
  app:
    build: 
      context: .
    ports:
      - "4000:4000"
    links:
      - db
    environment:
      - DB_URL=mongodb://db:27017/myLocalDatabase

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      # PORT: 8000
      MONGODB_URI: 'mongodb://db:27017/chayBackend'
      ACCESS_TOKEN_SECRET: chai-aur-code
      ACCESS_TOKEN_EXPIRY: 1d
      REFRESH_TOKEN_SECRET: chai-aur-backend
      REFRESH_TOKEN_EXPIRY: 10d
    ports:
      - 6000:6000


volumes:
  mongodata:


